applicantsDetails :{
    "applicantSalutation": "Mr.",
    "firstName": "aniket2",
    "middleName": "ram2",
    "lastName": "Bhosale2",
    "email": "shreyas@gmail.com",
    "contactNumber": "7894561231",
    "whatsappNumber": "123456789",
    "pancard": "pan123",
    "aadharCard": "aadhar123",
    "dob": "1991-02-05",
    "profession": "softwaredevloper",
    "age": 30,
    "permanentAddressLine1": "B - 003 Kishore Kunj 3",
    "permanentAddressLine2": null,
    "permanentCity": null,
    "permanentState": null,
    "permanentZipcode": null,
    "correspondenceAddressLine1": null,
    "correspondenceAddressLine2": null,
    "correspondenceCity": null,
    "correspondenceState": null,
    "correspondenceZipcode": null,
    "loaded": true,
    "residential_status": "Resident"
}

brokerDetails :{
    "broker": {
        "broker_id": "39",
        "brokerName": "broker 4"
    },
    "brokerList": [
        {
            "broker_id": "36",
            "brokerName": "Broker 1",
            "brokerNumber": "broker001",
            "brokerReraNumber": "brokerrera001",
            "status": "1"
        },
        {
            "broker_id": "37",
            "brokerName": "Broker 2",
            "brokerNumber": "2",
            "brokerReraNumber": "brokerrera002",
            "status": "1"
        },
        {
            "broker_id": "38",
            "brokerName": "broker 3",
            "brokerNumber": "3",
            "brokerReraNumber": "brokerrera003",
            "status": "1"
        },
        {
            "broker_id": "39",
            "brokerName": "broker 4",
            "brokerNumber": "4 ",
            "brokerReraNumber": "brokerreara004",
            "status": "1"
        }
    ],
    "createBoker": false,
    "brokerName": null,
    "brokerNumber": null,
    "brokerReraNumber": null,
    "brokerageType": "percentage",
    "brokerageValue": "60000.000",
    "brokeragePercentage": "2",
    "brokerageOn": "3000000.00",
    "brokerageArea": null,
    "brokerageSqft": null,
    "brokerageReraArea": null,
    "brokerageSaleableArea": 630,
    "brokerShow": true,
    "brokerageList": [
        {
            "broker_id": "39",
            "brokerName": "broker 4",
            "brokerageType": "percentage",
            "brokerageValue": "60000.000",
            "brokeragePercentage": "2",
            "brokerageOn": "3000000.00",
            "brokerageSqft": null,
            "brokerageArea": null
        }
    ],
    "bookingBy": "1",
    "bookingDate": "2021-12-04",
    "usersList": [
        {
            "user_id": "1",
            "name": "Jay shah"
        },
        {
            "user_id": "2",
            "name": null
        }
    ]
}

coApplicantsDetails :{
    "coapplicantSalutation": null,
    "firstName": null,
    "middleName": null,
    "lastName": null,
    "email": null,
    "contactNumber": null,
    "whatsappNumber": null,
    "pancard": null,
    "aadharCard": null,
    "dob": null,
    "profession": null,
    "age": null,
    "permanentAddressLine1": null,
    "permanentAddressLine2": null,
    "permanentCity": null,
    "permanentState": null,
    "permanentZipcode": null,
    "correspondenceAddressLine1": null,
    "correspondenceAddressLine2": null,
    "correspondenceCity": null,
    "correspondenceState": null,
    "correspondenceZipcode": null,
    "loaded": true,
    "allList": [],
    "residential_status": null
}

paymentDetails :{
    "arrays": [
        {
            "deal_id": "25",
            "project_id": "3",
            "name": "Package Deal",
            "model": "PackageDeal",
            "customer": "0",
            "office": "0",
            "type": "add",
            "totalConsideration": "nothing",
            "basicFlatCost": "nothing",
            "agreementValue": "add",
            "narration": "",
            "customerTotalConsideration": "nothing",
            "isForDemand": "0",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "1"
        },
        {
            "deal_id": "26",
            "project_id": "3",
            "name": "Basic Flat Cost",
            "model": "BasicFlatCost",
            "customer": "3000000.00",
            "office": "3000000",
            "type": "add",
            "totalConsideration": "add",
            "basicFlatCost": "nothing",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "1",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "2"
        },
        {
            "deal_id": "27",
            "project_id": "3",
            "name": "Infra / society",
            "model": "Society",
            "customer": "0",
            "office": "0",
            "type": "include",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "sub",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "1",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "3"
        },
        {
            "deal_id": "28",
            "project_id": "3",
            "name": "Document Charges",
            "model": "DocumentCharge",
            "customer": "0",
            "office": "0",
            "type": "sub",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "sub",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "1",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "4"
        },
        {
            "deal_id": "29",
            "project_id": "3",
            "name": "Maintainance",
            "model": "Maintainance",
            "customer": "0",
            "office": "0",
            "type": "sub",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "sub",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "1",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "5"
        },
        {
            "deal_id": "30",
            "project_id": "3",
            "name": "GST",
            "model": "Gst",
            "customer": "30000.00",
            "office": "30000.00",
            "type": "include",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "sub",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "6"
        },
        {
            "deal_id": "31",
            "project_id": "3",
            "name": "Stamp Duty",
            "model": "Stampduty",
            "customer": "150300.00",
            "office": "150300.00",
            "type": "include",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "sub",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "7"
        },
        {
            "deal_id": "32",
            "project_id": "3",
            "name": "Registration",
            "model": "Registration",
            "customer": "30000.00",
            "office": "30000.00",
            "type": "include",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "sub",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "8"
        },
        {
            "deal_id": "33",
            "project_id": "3",
            "name": "Furniture & Fixture",
            "model": "FurnitureFixture",
            "customer": "0",
            "office": "0",
            "type": "add",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "1",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "9"
        },
        {
            "deal_id": "34",
            "project_id": "3",
            "name": "Generator",
            "model": "Other",
            "customer": "0",
            "office": "0",
            "type": "add",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "1",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "10"
        },
        {
            "deal_id": "35",
            "project_id": "3",
            "name": "RoundOff",
            "model": "RoundOff",
            "customer": "0",
            "office": "0",
            "type": "add",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "1",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "11"
        },
        {
            "deal_id": "36",
            "project_id": "3",
            "name": "Other Charges",
            "model": "OtherCharges",
            "customer": "0",
            "office": "0",
            "type": "add",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "11"
        },
        {
            "deal_id": "37",
            "project_id": "3",
            "name": "Other Charges A",
            "model": "OtherChargesA",
            "customer": 0,
            "office": 0,
            "type": "add",
            "totalConsideration": "add",
            "basicFlatCost": "sub",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "add",
            "isForDemand": "0",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "11"
        },
        {
            "deal_id": "38",
            "project_id": "3",
            "name": "Discount",
            "model": "Discount",
            "customer": "0",
            "office": "0",
            "type": "sub",
            "totalConsideration": "sub",
            "basicFlatCost": "add",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "sub",
            "isForDemand": "0",
            "isEdit": "1",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "12"
        },
        {
            "deal_id": "39",
            "project_id": "3",
            "name": "Total Consideration",
            "model": "totalConsideration",
            "customer": "3210300.00",
            "office": "3210300.00",
            "type": "nothing",
            "totalConsideration": "nothing",
            "basicFlatCost": "add",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "nothing",
            "isForDemand": "1",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "13"
        },
        {
            "deal_id": "40",
            "project_id": "3",
            "name": "Agreement Value",
            "model": "AgreementValue",
            "customer": "3000000",
            "office": "3000000",
            "type": "nothing",
            "totalConsideration": "nothing",
            "basicFlatCost": "nothing",
            "agreementValue": "nothing",
            "narration": "",
            "customerTotalConsideration": "nothing",
            "isForDemand": "1",
            "isEdit": "0",
            "status": "1",
            "updated_at": "0000-00-00 00:00:00",
            "created_at": "2021-04-01 07:36:46",
            "created_by": "0",
            "order": "14"
        }
    ],
    "demandOn": {
        "name": "Basic Flat Cost",
        "value": "3000000.00"
    },
    "approxLoanAmount": "load amount",
    "paymentMode": "Outright",
    "additionalDescription": "additional description",
    "type": "manual",
    "loaded": false,
    "definedGst": 1,
    "definedStampduty": "5",
    "definedRegistration": "1",
    "customerAgreementValue": 0,
    "reraArea": null,
    "AreaSqft": "630",
    "ratePersqft": "4761.90",
    "reraPerSqft": "Infinity",
    "paymentTermsType": "regular",
    "customisePaymentTerms": [],
    "customisePercentage": 0,
    "apartments": [
        {
            "apartment_id": "416",
            "projectName": "Terado ",
            "buildingName": "Terado",
            "wingName": "A",
            "propertyType": "Flat",
            "facing": "East-West",
            "alloted": null,
            "tags": "[]",
            "reraCarpet": null,
            "balconyArea": null,
            "saleableArea": "630",
            "flatNo": "401",
            "flatIncrement": "100",
            "floorStartingFrom": "1",
            "minimumSellingRate": null,
            "status": "1",
            "floor": "4",
            "project_id": "3",
            "unit_type": "1BHK"
        }
    ],
    "apartment_id": "416",
    "wing": "A",
    "floor": "4",
    "flat": "401",
    "unit_type": "1BHK",
    "paymentTermsList": [
        {
            "payment_id": "6",
            "project_id": "3",
            "paymentTermsName": "Terado Payment Scheme",
            "status": "1",
            "startDate": null,
            "endDate": null,
            "project_name": "Terado "
        }
    ],
    "paymentTermsOption": "6",
    "additionalProperty": [],
    "additionalPropertySelect": null,
    "additionalPropertyFreeCount": 0,
    "additionalPropertyPaidCount": 0,
    "additionalPropertyAmount": 0,
    "additionalPropertyRate": 0,
    "gstNumber": "gstinnumber",
    "paymentTermsDetailList": [
        {
            "payment_details_id": "83",
            "payment_id": "6",
            "terms": "Booking",
            "type": "percentage",
            "percentage": "20",
            "status": "1",
            "created_at": "2021-04-01 07:39:31",
            "created_by": null,
            "updated_at": "0000-00-00 00:00:00",
            "due_date": "2021-04-16",
            "is_due_date": "1"
        },
        {
            "payment_details_id": "84",
            "payment_id": "6",
            "terms": "1st Slab",
            "type": "percentage",
            "percentage": "20",
            "status": "1",
            "created_at": "2021-04-01 07:39:31",
            "created_by": null,
            "updated_at": "0000-00-00 00:00:00",
            "due_date": "2021-04-16",
            "is_due_date": "1"
        },
        {
            "payment_details_id": "85",
            "payment_id": "6",
            "terms": "2nd Slab",
            "type": "percentage",
            "percentage": "20",
            "status": "1",
            "created_at": "2021-04-01 07:39:31",
            "created_by": null,
            "updated_at": "0000-00-00 00:00:00",
            "due_date": "2021-04-16",
            "is_due_date": "1"
        },
        {
            "payment_details_id": "86",
            "payment_id": "6",
            "terms": "3rd Slab",
            "type": "percentage",
            "percentage": "20",
            "status": "1",
            "created_at": "2021-04-01 07:39:31",
            "created_by": null,
            "updated_at": "0000-00-00 00:00:00",
            "due_date": "2021-04-16",
            "is_due_date": "1"
        },
        {
            "payment_details_id": "87",
            "payment_id": "6",
            "terms": "4th Slab",
            "type": "percentage",
            "percentage": "20",
            "status": "1",
            "created_at": "2021-04-01 07:39:31",
            "created_by": null,
            "updated_at": "0000-00-00 00:00:00",
            "due_date": "2021-04-16",
            "is_due_date": "1"
        }
    ],
    "additionalPropertyData": []
}